In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [4]:
#Import the data
data_path = "/bgfs/dgomez/dgomez/Santiago/Intro to Programming 2026/UCI Data/TCGA-PANCAN-HiSeq-801x20531"
rna_raw = pd.read_csv(data_path + "/data.csv", index_col=0)
labels = pd.read_csv(data_path + "/labels.csv", index_col=0)

In [5]:
print(f"Shape of Labels: {labels.shape}")
labels.head()

Shape of Labels: (801, 1)

         Class
sample_0  PRAD
sample_1  LUAD
sample_2  PRAD
sample_3  PRAD
sample_4  BRCA

In [6]:
print(f"Shape of Counts Data: {rna_raw.shape}")
rna_raw.head()

Shape of Counts Data: (801, 20531)

,gene_0,gene_1,gene_2,gene_3,gene_4,gene_5,gene_6,gene_7,gene_8,gene_9,...,gene_20521,gene_20522,gene_20523,gene_20524,gene_20525,gene_20526,gene_20527,gene_20528,gene_20529,gene_20530
sample_0,0.0,2.017209,3.265527,5.478487,10.431999,0.0,7.175175,0.591871,0.0,0.0,...,4.926711,8.210257,9.723516,7.220030,9.119813,12.003135,9.650743,8.921326,5.286759,0.0
sample_1,0.0,0.592732,1.588421,7.586157,9.623011,0.0,6.816049,0.000000,0.0,0.0,...,4.593372,7.323865,9.740931,6.256586,8.381612,12.674552,10.517059,9.397854,2.094168,0.0
sample_2,0.0,3.511759,4.327199,6.881787,9.870730,0.0,6.972130,0.452595,0.0,0.0,...,5.125213,8.127123,10.908640,5.401607,9.911597,9.045255,9.788359,10.090470,1.683023,0.0
sample_3,0.0,3.663618,4.507649,6.659068,10.196184,0.0,7.843375,0.434882,0.0,0.0,...,6.076566,8.792959,10.141520,8.942805,9.601208,11.392682,9.694814,9.684365,3.292001,0.0
sample_4,0.0,2.655741,2.821547,6.539454,9.738265,0.0,6.566967,0.360982,0.0,0.0,...,5.996032,8.891425,10.373790,7.181162,9.846910,11.922439,9.217749,9.461191,5.110372,0.0

In [8]:
x = rna_raw
y = labels

x_train, x_test, y_train, y_test = train_test_split(
    rna_raw, y, test_size=0.3, random_state=42, stratify=y
)

print(f"Training set: {X_train.shape[0]} samples")
print(f"Testing set: {X_test.shape[0]} samples")

print("\nTraining set Class composition:")
print(y_train.value_counts() * 100 / sum(y_train.value_counts()))
print("\nTresting set Class composition:")
print(y_test.value_counts() * 100 / sum(y_test.value_counts()))

Training set: 560 samples
Testing set: 241 samples

Training set Class composition:
Class
BRCA     37.500000
KIRC     18.214286
LUAD     17.678571
PRAD     16.964286
COAD      9.642857
Name: count, dtype: float64

Tresting set Class composition:
Class
BRCA     37.344398
KIRC     18.257261
LUAD     17.427386
PRAD     17.012448
COAD      9.958506
Name: count, dtype: float64

In [10]:
# save these as CSV files
x_train.to_csv("train_counts.csv")
y_train.to_csv("train_labels.csv")

x_test.to_csv("test_counts.csv")
y_test.to_csv("test_labels.csv")